#!/usr/bin/env python3.8
import re

words_11to12_hard = 'achieve, acoustics, action, advertisement, anoint, apparel, appliance, awkward,burglar, calculator, capital, ceiling, cemetery, conscious, constant, detrimental,dominant, eighth, exasperating, excel, exert, exhale, extravagant, facility, faucet,frugal, jealous, language, leather, manageable, medallion, medicinal, overrule,precious, preferred, pronounce, propel, receive, recitation, reign, retrieve,significance, similar, simplicity, sleight, texture, territory, treachery, vain, valiant,veil, vein, virtue, visual, wren, wring'
words_11to12_med = 'activity, afterthought, apartment, appoint, approve, beginner, boundary, breathe,calendar, caption, clothe, colony, competition, concern, condition, creature, crouton,currency, cycle, devotion, disguise, dishonest, distance, disuse, eager, education,exist, famous, feather, feature, fiction, fragile, friction, grateful, guardian, household,increase, industry, invention, junction, junior, lawyer, management, mayor,meanwhile, memorable, mention, metal, mightily, minister, nature, neither, option,pardon, passenger, pickle, picture, pleasure, popular, proceed, produce, professor,property, quartet, reason, recess, reduce, reduction, reply, route, scene, scent, stolen,supporter, sweater, teachable, televise, though, thread, tidal, triple, victory, volcano,wealth, weather, weird, wilderness, wrist'
words_11to12_easy = 'able, aftermath, afternoon, appear, attack, attend, breakfast, brightly, cabbage,cable, carpenter, channel, circle, climb, comfort, comical, confirm, construct, curtain,customer, damage, decide, delight, disappear, discover, empty, encourage, entertain,equal, exactly, forever, fruit, fuel, group, guard, guest, guide, guitar, handle, health,heart, heavily, helmet, idea, kindness, level, locket, lumber, magic, melon, meter,money, motor, mountain, partner, perfect, perhaps, personal, plastic, pocket,protect, provide, railway, record, reward, shoulder, socket, stranger, stroll, subject,suit, supply, temper, theatre, total, toward, treatment, useful, vacant, windy, writer'
words_9to10_hard = 'Arithmetic, avenue, beggar, bridge, caution, celery, cellar, century, chute, cough,couple, court, cousin, daughter, exercise, freight, fulfill, general, genius, gentle, giraffe, glacier, height, hydrant, icicle, image, issue, measles, nation, naughty, notion, ocean, plight, poise, poison, position, regular, remain, rough, scarce, statue, stockings, taught, throat, tomorrow, tough, unknown, unlikely, unusual, usual, value,vegetable, voyage, width'
words_9to10_med = 'Actor, addition, advice, against, ahead, amount, annual, answer, apiece, argue, author, avoid, beetle, borrow, breath, calm, canal, cannon, central, charge, collar, continue, creation, cried, daily, decorator, device, direction, earthquake, enough, excuse, fraction, furniture, ghost, guess, ignore, island, journal, judge, kept, ledge,lettuce, manage, mention, narrate, nineteen, noisy, often, palm, people, portion,praise, remark, repair, royal, shear, slept, station, steam, strange, stretch, sweat, terrible, themselves, thirsty, throne, tried, trouble, understand, until, vacation,visitor, vocal, wander, weave, whenever, whole'
words_9to10_easy = 'About, agree, above, across, alert, among, angry, annoy, another, award, aware, badge, basic, battle, beast, board, build, burst, cactus, careless, chase, chimney,circus, close, clothing, coach, coming, crawl, deaf, double, equal, evening, everything, flour, flower, froze, garbage, growl, hollow, honey, hoping, include, insist, jeans, kitchen, lace, laugh, little, marble, match, midnight, monkey, newspaper, offer, pillow, porch, recover, remember, report, riddle, scale, scrape, scream, seashore,season, shallow, shrimp, sidewalk, simple, slate, sleeve, stepped, stopped, strong, thrill, ticket, title, torch, trace, unlock, wonder, write'
words_7to8_hard = 'always, animal, around, because, before, believe, between, bread, bright, busy,cannot, caught, charge, clapped, clean, chicken, children, doctor, does, goes,everyone, everywhere, flight, inside, juice, kitchen, laughter, lunchroom, nobody,once, orange, outside, piece, purple, raise, round, shoes, today, used, weak, week,whale, which, while, wool, yesterday'
words_7to8_med = 'baseball, brother, can’t, clover, cloud, crayon, club, coat, come, cookie, could, crow,cube, cupcake, deal, dew, didn’t, dime, dine, dirt, doll, don’t, door, draw, dream,dress, drink, dull, each, east, easy, eight, eleven, every, father, field, fine, first, flew,flower, friend, globe, going, grape, grass, grew, heavy, I’m, it’s, know, marker, maybe,milk, morning, mother, myself, much, never, notebook, other, over, paper, pencil,pretty, rabbit, school, seven, sew, shirt, sister, smell, stray, string, summer, start,swing, table, thank, thrift, twelve, twist, under, very, water, were, where, won’t,yellow, zebra, zero'
words_7to8_easy = 'add, after, again, any, apple, arm, banana, bark, been, being, bent, best, bone, black,block, blue, bring, brown, bush, came, cane, card, cart, case, chain, chair, chalk, chat,chin, chop, clam, clan, clap, claw, clay, clean, cool, dark, desk, drop, end, family, fang,fast, fell, few, fill, flag, flat, fool, foot, fort, free, fresh, from, glad, golf, gone, grit, hand,hang, happy, harm, help, here, hide, hill, hint, hope, horn, how, ill, into, jaw, joke, just,keep, king, last, line, look, luck, made, many, meal, must, nice, new, next, odd, put,quit, rang, space, said, time, was, yard, yarn'
words_5to6_hard = 'fray, gray, play, bake, cake, lake, make, take, ate, date, gate, mate, rate, age, cage, give, gift, page, damp, lamp, stamp, here, there, tie, pie, bike, hike, like, kite, cry, dry, fry, try, paw, raw, saw, toe, hoe, bow, low, mow, crow, now, cow, bent, dent, tent, feet,beep, deep, jeep, peep, green, bold, cold, fold, hold, told, cone, bone, one, two, three,four, five, six, cube, tube, eat, heat, seat, dust, gust, must, paw, saw, find, kind, mind,bird, duck, frog, doll, game, toy, train, boat, plane, truck, ride, hide, wide, mine, ours,they, them, bowl, fork, spoon, home, pond, room, neck'
words_5to6_med = 'be, he, me, bee, see, she, we, go, so, do, chat, bar, car, far, cow, how, now, wow, hi, by, bye, dry, ox, box, fox, pox, egg, bay, day, may, say, way, all, ball, call, fall, tall, wall, as, ask, bask, task, with, had, have, bell, fell, well, book, cook, took, band, hand, land, say, said, are, jar, tar, car, best, pest, rest, test, bump, hump, jump, clump, baby, girl, boy,dog, name'
words_5to6_easy = 'a, at, bat, cat, rat, sat, an, can, fan, man, pan, ran, cap, map, nap, tap, bag, wag, tag, rag, am, jam, ram, yam, bad, dad, had, mad, sad, by, my, all, or, mum, and, us, bus, bed, red, get, let, jet, net, pet, wet, den, hen, pen, ten, beg, leg, peg, it, bit, fit, hit, sit, big, dig, fig, wig, in, fin, win, pin, bid, did, hid, rid, if, is, his, her, him, hip, sip, tip, lip, hop, mop, pop, top, dot, got, hot, not, pot, job, mob, sob, bun, fun, run, sun, but, cut, gut, nut, up, cup, pup, cub, rub, tub, bug, dug, hug, rug, tug, zoo'



new_list = [words_11to12_hard, words_11to12_med, words_11to12_easy, words_9to10_hard, words_9to10_med, words_9to10_easy, words_7to8_hard, words_7to8_med, words_7to8_easy, words_5to6_hard, words_5to6_med, words_5to6_easy]
new_file = open('levels.py', 'a+')

for id, list in enumerate(reversed(new_list)):
    new_file.write(f'list{id+1} = "')
    for word in list.split(','):
        match = re.search("’", word)
        if not match:
            word = word.strip(' ').strip().strip(',').lower()
            new_file.write(word + ' ')
    new_file.write('"\n')
